# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: warning
    unused_local_variable: warning
    unused_element: warning
    deprecated_member_use: info
    use_build_context_synchronously: info
    library_private_types_in_public_api: info
    curly_braces_in_flow_control_structures: info
    unnecessary_cast: warning
    creation_with_non_type: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "lib/generated/**"

linter:
  rules:
    prefer_single_quotes: true
